apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.10.10.10/32
  - 10.10.10.11/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-pool
